name = "context"
main = "build/server/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "context-db"
database_id = "55c25518-db3d-4547-8ad8-e36fc66493c8"

[assets]
directory = "build/client"

