name = "context"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2026-01-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "context-db"
database_id = "55c25518-db3d-4547-8ad8-e36fc66493c8"

[[d1_databases]]
binding = "PRIVATE_DB"
database_name = "private"
database_id = "de05bd43-f2be-41c5-8e4e-8d04fa4f4534"
